_commit: v1.1.0
_src_path: gh:mopidy/mopidy-ext-template
author_email: stein.magnus@jodal.no
author_full_name: Stein Magnus Jodal
dist_name: Mopidy-Spotify
ext_name: spotify
github_username: mopidy
repo_name: mopidy-spotify
short_description: Mopidy extension for playing music from Spotify
version: 5.0.0a3
